apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: ledger-api
  template:
    metadata:
      labels:
        component: ledger-api
    spec:
      containers:
        - name: ledger-api
          image: micrommath/ledger-ledger-api:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: shared-data
              mountPath: /logs
          env:
            - name: PORT
              value: "8080"
            - name: ACCOUNT_GRPC_ADDRESS
              value: "ledger-api-service:9001"
            - name: SERVICE_NAME
              value: "ledger-service"
            - name: ENVIRONMENT
              value: "production"
            - name: DB_HOST
              value: "ledger-db-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ledger-postgres-secrets
                  key: password
            - name: DB_NAME
              value: "Ledger"
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 60
            failureThreshold: 3
            httpGet:
              path: /api/healthz
              port: 8080                    
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 90
            failureThreshold: 3
            httpGet:
              path: /api/healthz
              port: 8080
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "200Mi"
              cpu: "300m"           
      volumes:
        - name: shared-data
          emptyDir: {}     