apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-service-sql-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS ledgers (
       Id SERIAL PRIMARY KEY,       
       Name VARCHAR(120),
       Document VARCHAR(14),       
       CreatedAt TIMESTAMP,
       UpdatedAt TIMESTAMP
    );