apiVersion: v1
kind: ConfigMap
metadata:
  name: ledger-service-sql-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS Transaction (
       Id SERIAL PRIMARY KEY,
       Description VARCHAR(120),
       CreatedAt TIMESTAMP
    );
    
    CREATE TABLE IF NOT EXISTS TransactionLine (
       Id SERIAL PRIMARY KEY,
       AccountId SERIAL,
       TransactionId SERIAL REFERENCES Transaction(Id),
       Amount BIGINT,
       EntryType VARCHAR(50),
       CreatedAt TIMESTAMP
    );

    -- Insert initial balance for account 01234567890
    INSERT INTO Transaction (Description, CreatedAt) 
    VALUES ('Initial credit for account 01234567890', CURRENT_TIMESTAMP);
    
    INSERT INTO TransactionLine (AccountId, TransactionId, Amount, EntryType, CreatedAt)
    VALUES (1, currval('transaction_id_seq'), 100000, 'CREDIT', CURRENT_TIMESTAMP);

    -- Insert initial balance for account 09876543210
    INSERT INTO Transaction (Description, CreatedAt) 
    VALUES ('Initial credit for account 09876543210', CURRENT_TIMESTAMP);
    
    INSERT INTO TransactionLine (AccountId, TransactionId, Amount, EntryType, CreatedAt)
    VALUES (2, currval('transaction_id_seq'), 100000, 'CREDIT', CURRENT_TIMESTAMP);