apiVersion: v1
kind: PersistentVolume
metadata:
  name: ledger-postgres-storage-pv
spec:
  storageClassName: ledger-postgres-storage-class
  capacity:
    storage: 400Mi
  hostPath:
    path: /mnt/data/ledger/postgres/
  accessModes:
    - ReadWriteMany
