apiVersion: v1
kind: Service
metadata:
  name: ledger-db-svc
  labels:
    component: ledger-postgres
spec:
  clusterIP: None
  selector:
    component: ledger-postgres
  ports:
    - port: 5432
      targetPort: 5432
