apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-storage-pv
spec:
  storageClassName: postgres-storage-class
  capacity:
    storage: 500Mi
  hostPath:
    path: /mnt/data/postgres/
  accessModes:
    - ReadWriteMany
