apiVersion: v1
kind: Service
metadata:
  name: account-api-service
spec:
  type: ClusterIP
  selector:    
      component: account-api
  ports:
  - name: http
    port: 9000
    targetPort: 8080
  - name: grpc
    port: 9001
    targetPort: 9001