name: go projects CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  account-service-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: CI account service
        uses: ./.github/actions/go-build-test
        with:
          working-dir: "./account-service"
