apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-sql-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS accounts (
       Id SERIAL PRIMARY KEY,
       Number VARCHAR(15),
       Name VARCHAR(120),
       Document VARCHAR(14),       
       CreatedAt TIMESTAMP,
       UpdatedAt TIMESTAMP
    );