apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-sql-scripts
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS accounts (
       Id SERIAL PRIMARY KEY,       
       Name VARCHAR(120),
       Document VARCHAR(14),       
       CreatedAt TIMESTAMP,
       UpdatedAt TIMESTAMP
    );

    -- Insert initial accounts
    INSERT INTO accounts (Name, Document, CreatedAt, UpdatedAt)
    VALUES 
      ('Account One', '01234567890', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
      ('Account Two', '09876543210', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);