apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-postgres-storage-pv
spec:
  storageClassName: account-postgres-storage-class
  capacity:
    storage: 400Mi
  hostPath:
    path: /mnt/data/postgres/
  accessModes:
    - ReadWriteMany
