apiVersion: v1
kind: Service
metadata:
  name: account-db-svc
  labels:
    component: account-postgres
spec:
  clusterIP: None
  selector:
    component: account-postgres
  ports:
    - port: 5432
      targetPort: 5432
